# Generated by Django 3.0.2 on 2020-11-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201115_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
